site_name: Documentation
site_description: |
  The documentation for NOMAD.
site_author: The NOMAD Authors
repo_url: https://github.com/FAIRmat-NFDI/pynxtools-spm
site_url: https://nomad-lab.eu/prod/v1/docs/index.html
edit_uri: ""
use_directory_urls: false
nav:
  - Home: index.md
  - Tutorial:
      - tutorials/installation.md
      - tutorials/reader-use-in-nomad.md
  - How-To-Guides: 
      - how-to-guides/how-to-use-the-reader.md
      - how-to-guides/how-to-extend-readers.md
  - Explanation: 
      - explanation/reader-orchestra.md
      - explanation/reader-structure.md
  - Reference: 
      - reference/standalon-usages.md
plugins:
  - search
  - macros:
      module_name: docs/macros
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  pallet:
    primary: "#2A4CDF"
  font:
    text: 'Titillium Web'
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.path
    - navigation.footer
    - navigation.top
  favicon: assets/favicon.png
  logo: assets/nomad-logo.png
  icon:
    repo: fontawesome/brands/github
extra: 
  generator: false
  homepage: https://nomad-lab.eu
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript.js