name: Backward Compatibility with Pynxtools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backward_compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pynxtools_versions: ["master"]
        python-versions: ["3.11"]
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Install uv && Set up Python ${{ matrix.python-versions }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-versions }}
          version: "0.6.2"


      - name: Install pip in the virtual environment
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          uv python get-pip.py

      - name: Install nomad
        if: "${{ matrix.python_version != '3.8'}}"
        run: |
          uv pip install nomad-lab[infrastructure]@git+https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git
          uv which python
          uv python --version


      - name: Install dependencies
        run: |
          uv python -m pip install --upgrade pip
          uv python -m pip install coverage coveralls
          uv which python

      - name: Install pynxtools-spm
        run: |
          uv which python
          uv python -c "import sys; print(sys.executable)"
          uv pip list | grep pynxtools
          uv pip install .[dev]
          uv which python
          uv python -c "import sys; print(sys.executable)"
          uv pip list | grep pynxtools

      - name: Install pynxtools version ${{ matrix.pynxtools_versions }}
        run: |
          uv which python
          uv python -c "import sys; print(sys.executable)"
          uv pip list | grep pynxtools
         
          if [ "${{ matrix.pynxtools_versions }}" == "master" ]; then
            echo "####### Installing pynxtools from master branch."
            uv pip install pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools@${{ matrix.pynxtools_versions }}
          else
           echo "####### released Installing pynxtools from master branch."
           uv pip install pynxtools==${{ matrix.pynxtools_versions }}
          fi
          
          uv which python
          uv python -c "import sys; print(sys.executable)"
          uv pip list | grep pynxtools

          if [ "${{ matrix.pynxtools_versions }}" == "master" ]; then
            echo "####### Installing pynxtools from master branch."
            uv pip install --force-reinstall pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools@${{ matrix.pynxtools_versions }}
          else
           echo "####### released Installing pynxtools from master branch."
           uv pip install --force-reinstall pynxtools==${{ matrix.pynxtools_versions }}
          fi

          uv which python
          uv python -c "import sys; print(sys.executable)"
          uv pip list | grep pynxtools

      - name: Run Reader tests
        run: |
          echo "### Running Check dependencies."
          uv which python
          uv pip list | grep pynxtools
          echo "#####"
          uv pytest tests/test_reader.py

      - name: Run Nomad Examples tests
        run: |
          echo "Running Check dependencies."
          uv pip list
          echo "Running Check dependencies."
          uv pytest tests/test_nomad_examples.py