name: Backward Compatibility with Pynxtools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backward_compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pynxtools_versions: ["master"]
        python-versions: ["3.11"]
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Install uv && Set up Python ${{ matrix.python-versions }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-versions }}
          version: "0.6.2"

      - name: Install Python
        run: uv python install

      - name: Install pip in the virtual environment
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          uv run python get-pip.py

      - name: Install nomad
        if: "${{ matrix.python_version != '3.8'}}"
        run: |
          uv run pip install nomad-lab[infrastructure]@git+https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git

      - name: Install dependencies
        run: |
          uv run python -m pip install --upgrade pip
          uv run python -m pip install coverage coveralls

      - name: Install pynxtools-spm
        run: |
          uv run pip install .[dev]

      - name: Install pynxtools version ${{ matrix.pynxtools_versions }}
        run: |
         if [ "${{ matrix.pynxtools_versions }}" == "master" ]; then
           uv run pip install pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools@${{ matrix.pynxtools_versions }}
         else
          uv run pip install pynxtools==${{ matrix.pynxtools_versions }}
         fi

      - name: Run Reader tests
        run: |
          echo "Running Check dependencies."
          uv run pip list
          uv run pytest tests/test_reader.py

      - name: Run Nomad Examples tests
        run: |
          echo "Running Check dependencies."
          uv run pip list
          echo "Running Check dependencies."
          uv run pytest tests/test_nomad_examples.py