name: Backward Compatibility with Pynxtools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backward_compatibility:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pynxtools_versions: ["master"]
        python-versions: ["3.11"]
 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      
      - name: Install uv && Set up Python ${{ matrix.python-versions }}
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-versions }}
          version: "0.6.2"

      - name: Install nomad
        if: "${{ matrix.python_version != '3.8'}}"
        run: |
          uv pip install nomad-lab[infrastructure]@git+https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git
          
          uv python --version


      - name: Install dependencies
        run: |
          uv pip install --upgrade pip
          uv pip install coverage coveralls
          

      - name: Install pynxtools-spm
        run: |
          
          
          uv pip list | grep pynxtools || echo "pynxtools not found"
          uv pip install .[dev]
          
          
          uv pip list | grep pynxtools || echo "pynxtools not found"

      - name: Install pynxtools version ${{ matrix.pynxtools_versions }}
        run: |
          
          
          uv pip list | grep pynxtools || echo "pynxtools not found"
         
          if [ "${{ matrix.pynxtools_versions }}" == "master" ]; then
            echo "####### Installing pynxtools from master branch."
            uv pip install pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools@${{ matrix.pynxtools_versions }}
          else
           echo "####### released Installing pynxtools from master branch."
           uv pip install pynxtools==${{ matrix.pynxtools_versions }}
          fi
          
          
          
          uv pip list | grep pynxtools || echo "pynxtools not found"

          if [ "${{ matrix.pynxtools_versions }}" == "master" ]; then
            echo "####### Installing pynxtools from master branch."
            uv pip install --force-reinstall pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools@${{ matrix.pynxtools_versions }}
          else
           echo "####### released Installing pynxtools from master branch."
           uv pip install --force-reinstall pynxtools==${{ matrix.pynxtools_versions }}
          fi

          
          uv pip list | grep pynxtools || echo "pynxtools not found"

      - name: Run Reader tests
        run: |
          echo "### Running Check dependencies."
          
          uv pip list | grep pynxtools || echo "pynxtools not found"
          uv pip list | grep nomad || echo "nomad not found"
          echo "#####"
          pytest tests/test_reader.py

      - name: Run Nomad Examples tests
        run: |
          echo "Running Check dependencies."
          uv pip list | grep pynxtools || echo "pynxtools not found"
          uv pip list | grep nomad || echo "nomad not found"
          echo "Running Check dependencies."
          pytest tests/test_nomad_examples.py