name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  UV_SYSTEM_PYTHON: true
  
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
        pynxtools_versions: ["master", "newVersionSPM"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Python ${{matrix.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python_version}}
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install pynxtools version ${{ matrix.pynxtools_versions }}
        run: |
          PYNXTOOLS_VERSION="${{ matrix.pynxtools_versions }}"
          uv pip uninstall pynxtools -q
          # Check for any branches
          if [[ ! "$PYNXTOOLS_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            uv pip install pynxtools@git+https://github.com/FAIRmat-NFDI/pynxtools@${{ matrix.pynxtools_versions }}
          elif [[ "$PYNXTOOLS_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            uv pip install pynxtools==${{ matrix.pynxtools_versions }}
          else
            uv pip install pynxtools
          fi
      - name: Install nomad
        run: |
          uv pip install nomad-lab[infrastructure]@git+https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR.git
      - name: Install package and dependencies
        run: |
          uv pip install .[dev]
      - name: Test pynxtools data conversion
        run: |
          pytest tests/test_reader.py
      - name: Test Nomad Examples
        if: "${{ matrix.python_version != '3.8'}}"
        run: |
          pytest tests/test_nomad_examples.py
